### PR TITLE
ENHANCEMENT cropper.js triggers

### PR DESCRIPTION
**Pull request by muskie9**
Allow developers to hook into `built` and `ready` for cropper plugin. I've included access to `field`, `target` and `preview` elements.

### CODE REVIEW

**Comment by dhensby** [comment]
Looks like the indentation is off

**Comment by muskie9** [comment]
Ah, right. I'll fix.

**Comment by muskie9** [comment]
Is js usually written w/spaces or tabs? PHPStorm had it as spaces, but tabs aligned in this case.

**Comment by dhensby** [comment]
> Is js usually written w/spaces or tabs? PHPStorm had it as spaces, but tabs aligned in this case.

Depends on the project :)

**Comment by willmorgan** [comment]
Thanks for this, @muskie9.

**Pull request merged**
